package com.sgr.dyg.test.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sgr.dyg.test.bean.MyLocation;
import com.sgr.dyg.test.bean.Student;

import com.sgr.dyg.test.greendao.MyLocationDao;
import com.sgr.dyg.test.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myLocationDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final MyLocationDao myLocationDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myLocationDaoConfig = daoConfigMap.get(MyLocationDao.class).clone();
        myLocationDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        myLocationDao = new MyLocationDao(myLocationDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(MyLocation.class, myLocationDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        myLocationDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public MyLocationDao getMyLocationDao() {
        return myLocationDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
